apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ebs-claim
  namespace: three-tier
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: postgres-sc
  resources:
    requests:
      storage: 20Gi